### ISSUE TITLE
TypeError: Cannot create a consistent method resolution order (MRO) for bases UserPassesTestMixin, ReportViewBase

### ISSUE THREAD

**Issue by virendracis** [RamezIssac/my-shop#2]
```python manage.py migrate
Traceback (most recent call last):
  File "/mnt/Extras/ERP/my-shop/manage.py", line 22, in <module>
    main()
  File "/mnt/Extras/ERP/my-shop/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/mnt/Extras/ERP/my-shop/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/mnt/Extras/ERP/my-shop/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/mnt/Extras/ERP/my-shop/venv/lib/python3.12/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/mnt/Extras/ERP/my-shop/venv/lib/python3.12/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/mnt/Extras/ERP/my-shop/request_analytics/apps.py", line 9, in ready
    from . import erp
  File "/mnt/Extras/ERP/my-shop/request_analytics/erp.py", line 6, in <module>
    from erp_framework.reporting.views import ReportView, ListReportView
  File "/mnt/Extras/ERP/my-shop/venv/src/django-erp-framework/erp_framework/reporting/views.py", line 213, in <module>
    class TimeSeriesSelectorReportView(UserPassesTestMixin, ReportViewBase):
TypeError: Cannot create a consistent method resolution
order (MRO) for bases UserPassesTestMixin, ReportViewBase
```

**Comment by Seeyouagainqz** [comment]
我也遇到了同样的问题

**Comment by xuemian168** [comment]
Same

**Comment by GamilYassin** [comment]
I had the same issue and as workaround to resolve it, had to change the parameters orders in TimeSeriesSelectorReportView class within "venv\src\django-erp-framework\erp_framework\reporting\views.py"

old class signature: class TimeSeriesSelectorReportView(UserPassesTestMixin, ReportViewBase):
new class signature: class TimeSeriesSelectorReportView(ReportViewBase, UserPassesTestMixin):

it works for now, but believe it needs to be fixed in django-erp-framework library itself
